#!/bin/bash

## Description: run blt in the web container
## Usage: blt [flags] [args]
## Example: "ddev blt" or "ddev mysql -uroot -proot" or "echo 'SHOW TABLES;' | ddev mysql"
## `ddev blt --database=mysql -uroot -proot` gets you to the 'mysql' database with root privileges

/var/www/html/vendor/acquia/blt/bin/blt $@
